builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.BuildTag={{.Version}} -X main.BuildCommit={{.Commit}} -X main.BuildDate={{.Date}}'
    goos:
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: 'rudi-lda_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    strip_parent_binary_folder: true
checksum:
  disable: true
